package pize.glfw.key;

import static org.lwjgl.glfw.GLFW.*;

public enum GBtn{

    GAMEPAD_A                  (GLFW_GAMEPAD_BUTTON_A           ),
    GAMEPAD_B                  (GLFW_GAMEPAD_BUTTON_B           ),
    GAMEPAD_X                  (GLFW_GAMEPAD_BUTTON_X           ),
    GAMEPAD_Y                  (GLFW_GAMEPAD_BUTTON_Y           ),
    GAMEPAD_LEFT_BUMPER        (GLFW_GAMEPAD_BUTTON_LEFT_BUMPER ),
    GAMEPAD_RIGHT_BUMPER       (GLFW_GAMEPAD_BUTTON_RIGHT_BUMPER),
    GAMEPAD_BACK               (GLFW_GAMEPAD_BUTTON_BACK        ),
    GAMEPAD_START              (GLFW_GAMEPAD_BUTTON_START       ),
    GAMEPAD_GUIDE              (GLFW_GAMEPAD_BUTTON_GUIDE       ),
    GAMEPAD_LEFT_THUMB         (GLFW_GAMEPAD_BUTTON_LEFT_THUMB  ),
    GAMEPAD_RIGHT_THUMB        (GLFW_GAMEPAD_BUTTON_RIGHT_THUMB ),
    GAMEPAD_DPAD_UP            (GLFW_GAMEPAD_BUTTON_DPAD_UP     ),
    GAMEPAD_DPAD_RIGHT         (GLFW_GAMEPAD_BUTTON_DPAD_RIGHT  ),
    GAMEPAD_DPAD_DOWN          (GLFW_GAMEPAD_BUTTON_DPAD_DOWN   ),
    GAMEPAD_DPAD_LEFT          (GLFW_GAMEPAD_BUTTON_DPAD_LEFT   ),
    GAMEPAD_CROSS              (GLFW_GAMEPAD_BUTTON_CROSS       ),
    GAMEPAD_CIRCLE             (GLFW_GAMEPAD_BUTTON_CIRCLE      ),
    GAMEPAD_SQUARE             (GLFW_GAMEPAD_BUTTON_SQUARE      ),
    GAMEPAD_TRIANGLE           (GLFW_GAMEPAD_BUTTON_TRIANGLE    ),
    GAMEPAD_AXIS_LEFT_X        (GLFW_GAMEPAD_AXIS_LEFT_X        ),
    GAMEPAD_AXIS_LEFT_Y        (GLFW_GAMEPAD_AXIS_LEFT_Y        ),
    GAMEPAD_AXIS_RIGHT_X       (GLFW_GAMEPAD_AXIS_RIGHT_X       ),
    GAMEPAD_AXIS_RIGHT_Y       (GLFW_GAMEPAD_AXIS_RIGHT_Y       ),
    GAMEPAD_AXIS_LEFT_TRIGGER  (GLFW_GAMEPAD_AXIS_LEFT_TRIGGER  ),
    GAMEPAD_AXIS_RIGHT_TRIGGER (GLFW_GAMEPAD_AXIS_RIGHT_TRIGGER );


    public final int GLFW;

    GBtn(int GLFW){
        this.GLFW = GLFW;
    }

}
