package pize.graphics.gl;

import static org.lwjgl.opengl.GL46.*;

public enum Attachment{
    
    DEPTH_ATTACHMENT(GL_DEPTH_ATTACHMENT),
    STENCIL_ATTACHMENT(GL_STENCIL_ATTACHMENT),
    
    COLOR_ATTACHMENT0(GL_COLOR_ATTACHMENT0),
    COLOR_ATTACHMENT1(GL_COLOR_ATTACHMENT1),
    COLOR_ATTACHMENT2(GL_COLOR_ATTACHMENT2),
    COLOR_ATTACHMENT3(GL_COLOR_ATTACHMENT3),
    COLOR_ATTACHMENT4(GL_COLOR_ATTACHMENT4),
    COLOR_ATTACHMENT5(GL_COLOR_ATTACHMENT5),
    COLOR_ATTACHMENT6(GL_COLOR_ATTACHMENT6),
    COLOR_ATTACHMENT7(GL_COLOR_ATTACHMENT7),
    COLOR_ATTACHMENT8(GL_COLOR_ATTACHMENT8),
    COLOR_ATTACHMENT9(GL_COLOR_ATTACHMENT9),
    
    COLOR_ATTACHMENT10(GL_COLOR_ATTACHMENT10),
    COLOR_ATTACHMENT11(GL_COLOR_ATTACHMENT11),
    COLOR_ATTACHMENT12(GL_COLOR_ATTACHMENT12),
    COLOR_ATTACHMENT13(GL_COLOR_ATTACHMENT13),
    COLOR_ATTACHMENT14(GL_COLOR_ATTACHMENT14),
    COLOR_ATTACHMENT15(GL_COLOR_ATTACHMENT15),
    COLOR_ATTACHMENT16(GL_COLOR_ATTACHMENT16),
    COLOR_ATTACHMENT17(GL_COLOR_ATTACHMENT17),
    COLOR_ATTACHMENT18(GL_COLOR_ATTACHMENT18),
    COLOR_ATTACHMENT19(GL_COLOR_ATTACHMENT19),
    
    COLOR_ATTACHMENT20(GL_COLOR_ATTACHMENT20),
    COLOR_ATTACHMENT21(GL_COLOR_ATTACHMENT21),
    COLOR_ATTACHMENT22(GL_COLOR_ATTACHMENT22),
    COLOR_ATTACHMENT23(GL_COLOR_ATTACHMENT23),
    COLOR_ATTACHMENT24(GL_COLOR_ATTACHMENT24),
    COLOR_ATTACHMENT25(GL_COLOR_ATTACHMENT25),
    COLOR_ATTACHMENT26(GL_COLOR_ATTACHMENT26),
    COLOR_ATTACHMENT27(GL_COLOR_ATTACHMENT27),
    COLOR_ATTACHMENT28(GL_COLOR_ATTACHMENT28),
    COLOR_ATTACHMENT29(GL_COLOR_ATTACHMENT29),
    
    COLOR_ATTACHMENT30(GL_COLOR_ATTACHMENT30),
    COLOR_ATTACHMENT31(GL_COLOR_ATTACHMENT31);
    
    
    public final int GL;
    
    Attachment(int GL){
        this.GL = GL;
    }
    
}
